GET http://127.0.0.1:8000/accounts/api/registration/data/ HTTP/1.1

###
POST http://127.0.0.1:8000/accounts/api/registration/data/ HTTP/1.1
content-type: application/json

{

    "company" : {
        "name": "sogo",
        "website": "http://127.0.0.1:8000/admin/emp/company/add/"
    }
    

  }



###
GET http://127.0.0.1:8000/api/api/companies/1 HTTP/1.1

###
PATCH http://127.0.0.1:8000/api/api/companies/2/ HTTP/1.1
Content-Type: application/json

{
    "name": "ghi"

}




###
DELETE http://127.0.0.1:8000/api/api/companies/2/ HTTP/1.1

###
GET http://127.0.0.1:8000/api/api/companies?search= HTTP/1.1





