# Generated by Django 3.2.19 on 2024-06-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20230615_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='jobfair',
            name='venue',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=255),
        ),
    ]
