# Generated by Django 4.2 on 2024-01-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0013_auto_20230615_1128"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
