# Generated by Django 4.2 on 2024-01-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0014_alter_event_options_alter_testimonial_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.CharField(default="", max_length=255),
        ),
    ]
