# Generated by Django 3.2.19 on 2025-10-21 08:50

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('emp', '0065_auto_20230705_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Designation (Job Position)')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Job Description')),
                ('salary_range_min', models.IntegerField(blank=True, null=True, verbose_name='Annual Salary (Minimum)')),
                ('salary_range_max', models.IntegerField(blank=True, null=True, verbose_name='Annual Salary (Maximum)')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('waiting_for_approval', 'Waiting for Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=50)),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Qualifications/Skills Required')),
                ('key_job_responsibilities', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Key Job Responsibilities')),
                ('last_app_date', models.DateTimeField(verbose_name='Last Application Date')),
                ('num_vacancies', models.IntegerField(blank=True, default=1, null=True)),
                ('gender', models.CharField(choices=[('a', 'No Criteria'), ('f', 'F-Female Candidates'), ('m', 'M-Male Candidates')], default='a', max_length=10)),
                ('city', models.ManyToManyField(related_name='jobs', to='common.City')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.company')),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.domain', verbose_name='Job Sector')),
                ('job_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobtype')),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(choices=[(2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], null=True),
        ),
        migrations.CreateModel(
            name='JobEligibleState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_states_map', to='emp.jobdetail')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_jobs_map', to='common.state')),
            ],
            options={
                'unique_together': {('job', 'state')},
            },
        ),
        migrations.CreateModel(
            name='JobEligibleFoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spk_foss_id', models.IntegerField(db_index=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_courses_map', to='emp.jobdetail')),
            ],
            options={
                'unique_together': {('job', 'spk_foss_id')},
            },
        ),
        migrations.CreateModel(
            name='JobEligiblCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_jobs_map', to='common.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligible_cities_map', to='emp.jobdetail')),
            ],
            options={
                'unique_together': {('job', 'city')},
            },
        ),
    ]
