# Generated by Django 3.2.19 on 2024-06-10 08:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('utilities', '0003_institutetype_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp', '0065_auto_20230705_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Designation (Job Position)')),
                ('salary_range_min', models.IntegerField(blank=True, null=True, verbose_name='Annual Salary (Minimum)')),
                ('salary_range_max', models.IntegerField(blank=True, null=True, verbose_name='Annual Salary (Maximum)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'pending approval'), ('published', 'Published'), ('closed', 'Closed'), ('deleted', 'Deleted'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Job Description')),
                ('requirements', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Qualifications/Skills Required')),
                ('key_job_responsibilities', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Key Job Responsibilities')),
                ('shift_time', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('a', 'No Criteria'), ('f', 'F-Female Candidates'), ('m', 'M-Male Candidates')], default='a', max_length=10)),
                ('last_application_date', models.DateField(blank=True, null=True)),
                ('num_vacancies', models.IntegerField(blank=True, default=1, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.city')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-date_created', '-date_updated')},
        ),
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='city_c',
        ),
        migrations.RemoveField(
            model_name='company',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state_c',
        ),
        migrations.AddField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_companies', to='emp.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.location'),
        ),
        migrations.AddField(
            model_name='company',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobshortlist',
            name='app_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted By JRS Admin', 'Shortlisted By JRS Admin'), ('Rejected By JRS Admin', 'Rejected By JRS Admin'), ('Shortlisted By Employer', 'Shortlisted By Employer'), ('Rejected By Employer', 'Rejected By Employer'), ('Job Offered', 'Job Offered'), ('Accepted Offer', 'Accepted Offer'), ('Rejected Offer', 'Rejected Offer')], default='Applied', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(choices=[(2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], null=True),
        ),
        migrations.RemoveField(
            model_name='job',
            name='city_job',
        ),
        migrations.AddField(
            model_name='job',
            name='city_job',
            field=models.ManyToManyField(related_name='jobs1', to='utilities.City'),
        ),
        migrations.AlterField(
            model_name='job',
            name='degree',
            field=models.ManyToManyField(blank=True, null=True, related_name='degrees1', to='emp.Degree'),
        ),
        migrations.AlterField(
            model_name='job',
            name='discipline',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplines1', to='emp.Discipline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_foss',
            field=models.ManyToManyField(blank=True, null=True, related_name='fosses1', to='emp.Foss'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_app_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Application Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs1', to='emp.Skill'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'pending approval'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobshortlist',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.job'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.skillgroup'),
        ),
        migrations.CreateModel(
            name='StudentFilterInstituteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('insti_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.institutetype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
            ],
        ),
        migrations.CreateModel(
            name='JobShortlistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted By JRS Admin', 'Shortlisted By JRS Admin'), ('Rejected By JRS Admin', 'Rejected By JRS Admin'), ('Shortlisted By Employer', 'Shortlisted By Employer'), ('Rejected By Employer', 'Rejected By Employer'), ('Job Offered', 'Job Offered'), ('Accepted Offer', 'Accepted Offer'), ('Rejected Offer', 'Rejected Offer')], max_length=100)),
                ('status_changed_to', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted By JRS Admin', 'Shortlisted By JRS Admin'), ('Rejected By JRS Admin', 'Rejected By JRS Admin'), ('Shortlisted By Employer', 'Shortlisted By Employer'), ('Rejected By Employer', 'Rejected By Employer'), ('Job Offered', 'Job Offered'), ('Accepted Offer', 'Accepted Offer'), ('Rejected Offer', 'Rejected Offer')], max_length=100)),
                ('job_shortlist_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobshortlist')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobGraduatingYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='JobFilterYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
            ],
        ),
        migrations.CreateModel(
            name='JobFilterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.state')),
            ],
        ),
        migrations.CreateModel(
            name='JobFilterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.state')),
            ],
        ),
        migrations.CreateModel(
            name='JobFilterCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
            ],
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.company'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='degree',
            field=models.ManyToManyField(blank=True, null=True, related_name='degrees', to='emp.Degree'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='discipline',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplines', to='emp.Discipline'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.domain', verbose_name='Job Sector'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobtype'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='emp.Skill'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='state_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.state'),
        ),
        migrations.CreateModel(
            name='CompanyManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobshortlist',
            name='job_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail'),
        ),
        migrations.CreateModel(
            name='StudentFilterYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
            ],
            options={
                'unique_together': {('job', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StudentFilterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='emp.jobdetail')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.state')),
            ],
            options={
                'unique_together': {('job', 'city')},
            },
        ),
        migrations.CreateModel(
            name='StudentFilterFoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Optional', 'Optional')], default='Mandatory', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('grade', models.IntegerField(blank=True, default=60, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.fosscategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
            ],
            options={
                'unique_together': {('job', 'foss')},
            },
        ),
        migrations.CreateModel(
            name='JobFoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Optional', 'Optional')], default='Mandatory', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('grade', models.IntegerField(blank=True, default=60, null=True)),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.fosscategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
            ],
            options={
                'unique_together': {('job', 'foss')},
            },
        ),
    ]
