# Generated by Django 3.2.19 on 2025-07-13 08:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filters', '0001_initial'),
        ('emp', '0065_auto_20230705_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='cities',
            field=models.ManyToManyField(related_name='jobs', to='filters.City'),
        ),
        migrations.AddField(
            model_name='job',
            name='city_of_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='filters.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='course_groups',
            field=models.ManyToManyField(related_name='jobs', to='filters.FossSuperCategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='courses',
            field=models.ManyToManyField(related_name='jobs', to='filters.FossCategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='degrees',
            field=models.ManyToManyField(related_name='jobs', to='filters.Degree'),
        ),
        migrations.AddField(
            model_name='job',
            name='disciplines',
            field=models.ManyToManyField(related_name='jobs', to='filters.Discipline'),
        ),
        migrations.AddField(
            model_name='job',
            name='graduation_years',
            field=models.ManyToManyField(related_name='jobs', to='filters.GraduationYear'),
        ),
        migrations.AddField(
            model_name='job',
            name='institute_types',
            field=models.ManyToManyField(related_name='jobs', to='filters.InstituteType'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Pending Approval'), (2, 'Active'), (3, 'Rejected'), (4, 'Expired')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='state_of_job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='filters.state'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='states',
            field=models.ManyToManyField(related_name='jobs', to='filters.State'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.IntegerField(choices=[(2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029)], null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], null=True),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Invalid.', regex='^\\+?1?\\d{9,15}$')])),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employers_added', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this employer (null if self-approved via email)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employers_approved', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emp.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
