# Generated by Django 3.2.19 on 2023-11-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        ('emp', '0065_auto_20230705_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_companies', to='emp.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_app_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Application Date'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.skillgroup'),
        ),
        migrations.CreateModel(
            name='JobFoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mandatory', 'Mandatory'), ('Optional', 'Optional')], default='Mandatory', max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('foss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.fosscategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.job')),
            ],
        ),
    ]
