# Generated by Django 3.2.19 on 2023-11-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0068_companymanagers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'pending approval'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
