# Generated by Django 3.2.19 on 2025-07-13 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp', '0068_alter_employer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='employer',
            name='status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active')], default=0),
        ),
        migrations.AddField(
            model_name='jobshortlist',
            name='application_status',
            field=models.IntegerField(blank=True, choices=[(0, 'in process'), (1, 'approved by admin'), (2, 'rejected by admin'), (3, 'approved by employer'), (4, 'rejected by employer')], null=True),
        ),
        migrations.CreateModel(
            name='JobShortlistLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_status', models.IntegerField()),
                ('final_status', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.job')),
                ('status_changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.student')),
            ],
        ),
    ]
