# Generated by Django 3.2.19 on 2025-07-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0069_auto_20250713_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending Approval'), (2, 'Active'), (3, 'Rejected'), (4, 'Expired')], default=0, max_length=255),
        ),
    ]
