# Generated by Django 3.2.19 on 2025-07-14 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
        ('emp', '0070_alter_job_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='filters.City'),
        ),
        migrations.AlterField(
            model_name='job',
            name='city_of_job',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='filters.city'),
        ),
        migrations.AlterField(
            model_name='job',
            name='course_groups',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='filters.FossSuperCategory'),
        ),
        migrations.AlterField(
            model_name='job',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='filters.FossCategory'),
        ),
        migrations.AlterField(
            model_name='job',
            name='degrees',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='filters.Degree'),
        ),
        migrations.AlterField(
            model_name='job',
            name='disciplines',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='filters.Discipline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='graduation_years',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='filters.GraduationYear'),
        ),
        migrations.AlterField(
            model_name='job',
            name='institute_types',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='filters.InstituteType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emp.jobtype'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_app_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Application Date'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state_of_job',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='filters.state'),
        ),
        migrations.AlterField(
            model_name='job',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='filters.State'),
        ),
    ]
