# Generated by Django 3.2.19 on 2025-07-14 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
        ('emp', '0071_auto_20250714_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city_of_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filters.city'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state_of_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filters.state'),
        ),
    ]
