# Generated by Django 4.2.7 on 2023-12-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("utilities", "0002_state_district_city"),
        ("emp", "0072_alter_job_city_job"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="city_job",
        ),
        migrations.AddField(
            model_name="job",
            name="city_job",
            field=models.ManyToManyField(related_name="jobs", to="utilities.city"),
        ),
    ]
