# Generated by Django 4.2.7 on 2023-12-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp", "0073_remove_job_city_job_job_city_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="show_on_homepage",
            field=models.BooleanField(default=True),
        ),
    ]
