# Generated by Django 3.2.19 on 2024-01-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0075_auto_20240116_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobshortlist',
            name='app_status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20),
        ),
    ]
