# Generated by Django 3.2.19 on 2024-03-14 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emp', '0078_alter_studentfilterlocation_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='added_by',
            field=models.ForeignKey(default=14704, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
