# Generated by Django 3.2.19 on 2024-04-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_institutetype_location'),
        ('emp', '0082_alter_jobdetail_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymanagers',
            name='phone',
            field=models.CharField(default=9810150179, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobfiltercity',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail'),
        ),
        migrations.AlterField(
            model_name='jobfilterstate',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail'),
        ),
        migrations.AlterField(
            model_name='jobfilteryear',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail'),
        ),
        migrations.AlterField(
            model_name='jobfoss',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail'),
        ),
        migrations.AlterField(
            model_name='jobgraduatingyear',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail'),
        ),
        migrations.CreateModel(
            name='JobFilterLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.city')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.jobdetail')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.state')),
            ],
        ),
    ]
