# Generated by Django 3.2.19 on 2024-04-03 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_institutetype_location'),
        ('emp', '0083_auto_20240403_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city_c',
        ),
        migrations.RemoveField(
            model_name='company',
            name='state_c',
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.location'),
        ),
    ]
