# Generated by Django 3.2.19 on 2024-04-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0084_auto_20240403_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='address',
            new_name='location',
        ),
    ]
