# Generated by Django 3.2.19 on 2024-04-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0085_rename_address_company_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='last_app_date',
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='last_application_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
